name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_HUB_CRUD_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_CRUD_USER }} --password-stdin

      - name: Get version from current timestamp
        id: get_version
        run: echo "::set-output name=version::$(date +%s)"
             
      - name: Build and tag Docker image
        id: build_image
        run: |
          docker build . --file Dockerfile --tag denktmiteg/postgresql-client-13.11:latest --tag denktmiteg/postgresql-client:${{ steps.get_version.outputs.version }}
          
      - name: Push Docker image
        run: |
          docker push denktmiteg/postgresql-client-13.11:latest
          docker push denktmiteg/postgresql-client-13.11:${{ steps.get_version.outputs.version }}
